/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConversationRouteImport } from './routes/conversation'
import { Route as TabsRouteImport } from './routes/_tabs'
import { Route as TabsIndexRouteImport } from './routes/_tabs.index'
import { Route as EvaluationIdRouteImport } from './routes/evaluation.$id'
import { Route as TabsUpdatesRouteImport } from './routes/_tabs.updates'
import { Route as TabsMessagesRouteImport } from './routes/_tabs.messages'
import { Route as TabsChildrenRouteImport } from './routes/_tabs.children'
import { Route as TabsCalendarRouteImport } from './routes/_tabs.calendar'
import { Route as TabsAccountRouteImport } from './routes/_tabs.account'
import { Route as TabsAccountIndexRouteImport } from './routes/_tabs.account.index'
import { Route as TabsAccountSecurityRouteImport } from './routes/_tabs.account.security'
import { Route as TabsAccountProfileRouteImport } from './routes/_tabs.account.profile'
import { Route as TabsAccountPreferencesRouteImport } from './routes/_tabs.account.preferences'
import { Route as TabsAccountPaymentsRouteImport } from './routes/_tabs.account.payments'
import { Route as TabsAccountHelpRouteImport } from './routes/_tabs.account.help'
import { Route as TabsAccountChildrenRouteImport } from './routes/_tabs.account.children'

const ConversationRoute = ConversationRouteImport.update({
  id: '/conversation',
  path: '/conversation',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsRoute = TabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsIndexRoute = TabsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TabsRoute,
} as any)
const EvaluationIdRoute = EvaluationIdRouteImport.update({
  id: '/evaluation/$id',
  path: '/evaluation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsUpdatesRoute = TabsUpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => TabsRoute,
} as any)
const TabsMessagesRoute = TabsMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => TabsRoute,
} as any)
const TabsChildrenRoute = TabsChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => TabsRoute,
} as any)
const TabsCalendarRoute = TabsCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => TabsRoute,
} as any)
const TabsAccountRoute = TabsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => TabsRoute,
} as any)
const TabsAccountIndexRoute = TabsAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TabsAccountRoute,
} as any)
const TabsAccountSecurityRoute = TabsAccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => TabsAccountRoute,
} as any)
const TabsAccountProfileRoute = TabsAccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TabsAccountRoute,
} as any)
const TabsAccountPreferencesRoute = TabsAccountPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => TabsAccountRoute,
} as any)
const TabsAccountPaymentsRoute = TabsAccountPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => TabsAccountRoute,
} as any)
const TabsAccountHelpRoute = TabsAccountHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => TabsAccountRoute,
} as any)
const TabsAccountChildrenRoute = TabsAccountChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => TabsAccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof TabsIndexRoute
  '/conversation': typeof ConversationRoute
  '/account': typeof TabsAccountRouteWithChildren
  '/calendar': typeof TabsCalendarRoute
  '/children': typeof TabsChildrenRoute
  '/messages': typeof TabsMessagesRoute
  '/updates': typeof TabsUpdatesRoute
  '/evaluation/$id': typeof EvaluationIdRoute
  '/account/children': typeof TabsAccountChildrenRoute
  '/account/help': typeof TabsAccountHelpRoute
  '/account/payments': typeof TabsAccountPaymentsRoute
  '/account/preferences': typeof TabsAccountPreferencesRoute
  '/account/profile': typeof TabsAccountProfileRoute
  '/account/security': typeof TabsAccountSecurityRoute
  '/account/': typeof TabsAccountIndexRoute
}
export interface FileRoutesByTo {
  '/conversation': typeof ConversationRoute
  '/calendar': typeof TabsCalendarRoute
  '/children': typeof TabsChildrenRoute
  '/messages': typeof TabsMessagesRoute
  '/updates': typeof TabsUpdatesRoute
  '/evaluation/$id': typeof EvaluationIdRoute
  '/': typeof TabsIndexRoute
  '/account/children': typeof TabsAccountChildrenRoute
  '/account/help': typeof TabsAccountHelpRoute
  '/account/payments': typeof TabsAccountPaymentsRoute
  '/account/preferences': typeof TabsAccountPreferencesRoute
  '/account/profile': typeof TabsAccountProfileRoute
  '/account/security': typeof TabsAccountSecurityRoute
  '/account': typeof TabsAccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_tabs': typeof TabsRouteWithChildren
  '/conversation': typeof ConversationRoute
  '/_tabs/account': typeof TabsAccountRouteWithChildren
  '/_tabs/calendar': typeof TabsCalendarRoute
  '/_tabs/children': typeof TabsChildrenRoute
  '/_tabs/messages': typeof TabsMessagesRoute
  '/_tabs/updates': typeof TabsUpdatesRoute
  '/evaluation/$id': typeof EvaluationIdRoute
  '/_tabs/': typeof TabsIndexRoute
  '/_tabs/account/children': typeof TabsAccountChildrenRoute
  '/_tabs/account/help': typeof TabsAccountHelpRoute
  '/_tabs/account/payments': typeof TabsAccountPaymentsRoute
  '/_tabs/account/preferences': typeof TabsAccountPreferencesRoute
  '/_tabs/account/profile': typeof TabsAccountProfileRoute
  '/_tabs/account/security': typeof TabsAccountSecurityRoute
  '/_tabs/account/': typeof TabsAccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conversation'
    | '/account'
    | '/calendar'
    | '/children'
    | '/messages'
    | '/updates'
    | '/evaluation/$id'
    | '/account/children'
    | '/account/help'
    | '/account/payments'
    | '/account/preferences'
    | '/account/profile'
    | '/account/security'
    | '/account/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/conversation'
    | '/calendar'
    | '/children'
    | '/messages'
    | '/updates'
    | '/evaluation/$id'
    | '/'
    | '/account/children'
    | '/account/help'
    | '/account/payments'
    | '/account/preferences'
    | '/account/profile'
    | '/account/security'
    | '/account'
  id:
    | '__root__'
    | '/_tabs'
    | '/conversation'
    | '/_tabs/account'
    | '/_tabs/calendar'
    | '/_tabs/children'
    | '/_tabs/messages'
    | '/_tabs/updates'
    | '/evaluation/$id'
    | '/_tabs/'
    | '/_tabs/account/children'
    | '/_tabs/account/help'
    | '/_tabs/account/payments'
    | '/_tabs/account/preferences'
    | '/_tabs/account/profile'
    | '/_tabs/account/security'
    | '/_tabs/account/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TabsRoute: typeof TabsRouteWithChildren
  ConversationRoute: typeof ConversationRoute
  EvaluationIdRoute: typeof EvaluationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/conversation': {
      id: '/conversation'
      path: '/conversation'
      fullPath: '/conversation'
      preLoaderRoute: typeof ConversationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs': {
      id: '/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs/': {
      id: '/_tabs/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof TabsIndexRouteImport
      parentRoute: typeof TabsRoute
    }
    '/evaluation/$id': {
      id: '/evaluation/$id'
      path: '/evaluation/$id'
      fullPath: '/evaluation/$id'
      preLoaderRoute: typeof EvaluationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs/updates': {
      id: '/_tabs/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof TabsUpdatesRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/messages': {
      id: '/_tabs/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof TabsMessagesRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/children': {
      id: '/_tabs/children'
      path: '/children'
      fullPath: '/children'
      preLoaderRoute: typeof TabsChildrenRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/calendar': {
      id: '/_tabs/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof TabsCalendarRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/account': {
      id: '/_tabs/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof TabsAccountRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/account/': {
      id: '/_tabs/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof TabsAccountIndexRouteImport
      parentRoute: typeof TabsAccountRoute
    }
    '/_tabs/account/security': {
      id: '/_tabs/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof TabsAccountSecurityRouteImport
      parentRoute: typeof TabsAccountRoute
    }
    '/_tabs/account/profile': {
      id: '/_tabs/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof TabsAccountProfileRouteImport
      parentRoute: typeof TabsAccountRoute
    }
    '/_tabs/account/preferences': {
      id: '/_tabs/account/preferences'
      path: '/preferences'
      fullPath: '/account/preferences'
      preLoaderRoute: typeof TabsAccountPreferencesRouteImport
      parentRoute: typeof TabsAccountRoute
    }
    '/_tabs/account/payments': {
      id: '/_tabs/account/payments'
      path: '/payments'
      fullPath: '/account/payments'
      preLoaderRoute: typeof TabsAccountPaymentsRouteImport
      parentRoute: typeof TabsAccountRoute
    }
    '/_tabs/account/help': {
      id: '/_tabs/account/help'
      path: '/help'
      fullPath: '/account/help'
      preLoaderRoute: typeof TabsAccountHelpRouteImport
      parentRoute: typeof TabsAccountRoute
    }
    '/_tabs/account/children': {
      id: '/_tabs/account/children'
      path: '/children'
      fullPath: '/account/children'
      preLoaderRoute: typeof TabsAccountChildrenRouteImport
      parentRoute: typeof TabsAccountRoute
    }
  }
}

interface TabsAccountRouteChildren {
  TabsAccountChildrenRoute: typeof TabsAccountChildrenRoute
  TabsAccountHelpRoute: typeof TabsAccountHelpRoute
  TabsAccountPaymentsRoute: typeof TabsAccountPaymentsRoute
  TabsAccountPreferencesRoute: typeof TabsAccountPreferencesRoute
  TabsAccountProfileRoute: typeof TabsAccountProfileRoute
  TabsAccountSecurityRoute: typeof TabsAccountSecurityRoute
  TabsAccountIndexRoute: typeof TabsAccountIndexRoute
}

const TabsAccountRouteChildren: TabsAccountRouteChildren = {
  TabsAccountChildrenRoute: TabsAccountChildrenRoute,
  TabsAccountHelpRoute: TabsAccountHelpRoute,
  TabsAccountPaymentsRoute: TabsAccountPaymentsRoute,
  TabsAccountPreferencesRoute: TabsAccountPreferencesRoute,
  TabsAccountProfileRoute: TabsAccountProfileRoute,
  TabsAccountSecurityRoute: TabsAccountSecurityRoute,
  TabsAccountIndexRoute: TabsAccountIndexRoute,
}

const TabsAccountRouteWithChildren = TabsAccountRoute._addFileChildren(
  TabsAccountRouteChildren,
)

interface TabsRouteChildren {
  TabsAccountRoute: typeof TabsAccountRouteWithChildren
  TabsCalendarRoute: typeof TabsCalendarRoute
  TabsChildrenRoute: typeof TabsChildrenRoute
  TabsMessagesRoute: typeof TabsMessagesRoute
  TabsUpdatesRoute: typeof TabsUpdatesRoute
  TabsIndexRoute: typeof TabsIndexRoute
}

const TabsRouteChildren: TabsRouteChildren = {
  TabsAccountRoute: TabsAccountRouteWithChildren,
  TabsCalendarRoute: TabsCalendarRoute,
  TabsChildrenRoute: TabsChildrenRoute,
  TabsMessagesRoute: TabsMessagesRoute,
  TabsUpdatesRoute: TabsUpdatesRoute,
  TabsIndexRoute: TabsIndexRoute,
}

const TabsRouteWithChildren = TabsRoute._addFileChildren(TabsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  TabsRoute: TabsRouteWithChildren,
  ConversationRoute: ConversationRoute,
  EvaluationIdRoute: EvaluationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
